name = "Psychro"
uuid = "9516f557-4a54-5a79-b954-c272e753c77a"
authors = ["Paulo Jabardo"]
version = "0.2.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "^1.4.1"
julia = "^1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
